include: "/Control_Report_Folder/Control_Report_Model/MICA_CONTROL_REPORT.view"
include: "/Control_Report_Folder/Control_Report_Model/SARACEN_GRCA_CONTROL_REPORT.view"
include : "/Control_Report_Folder/Control_Report_Model/fotc_rd_bfa_mia_results_preview_prior_submission.view"
include: "/Control_Report_Folder/Control_Report_Model/fotc_rd_bfa_saracen_results_preview_prior_submission.view"
include: "/Control_Report_Folder/Control_Report_Model/fotc_iaa_summary_mapping_exception.view.lkml"
include: "/Control_Report_Folder/Control_Report_Model/fotc_rd_mi_flat_dimension_mi_entity_control.view"
include: "/Control_Report_Folder/Control_Report_Model/fotc_rd_mi_flat_dimension_mi_entity_control.view"
# Add fotc_dp_ce_gl_detail_output_current_period_manual_adjustments by Jim on 11Jan2023
include: "/Control_Report_Folder/Control_Report_Model/fotc_dp_ce_gl_detail_adjustment.view"
# C10 from Jim on 7Feb2023
include: "/Control_Report_Folder/Control_Report_Model/fotc_dp_bfa_balance_traceability_dashboard_grca_mtd.view"
#include: "/Control_Report_Folder/Control_Report_Model/FOTC_RD_BFA_MI_COMBINED_DIMENSIONS.view.lkml"
